
site_name: Frizzy's Wiki
pages:
  - Frizzy's Wiki: index.md
  - Plataforma: 
    - Arduino: arduino.md
    - Raspberry Pi: raspberry.md
  - Frizzy Elemental Kit: 
    - Introducción :  intro.md
    - Grape: grape.md
    - Sensores:
      - Boton: boton.md
      - Sensor de luz: ldr.md
      - Potenciómetro: pot.md
      - Sensor de distancia: sharp.md
      - Sensor siguelineas: linefollower.md
      - Keypad: keypad.md
    - Actuadores:
      - Controlador de motores: motor.md
      - Led RGB: rgb.md
      - Buzzer: buzzer.md
      - Led: led.md
      - Servo: servo.md
    - Display:
      - Pantalla Oled: oled.md
    - Communicacion:
      - Módulo bluetooth: bluetooth.md
    - Otros: otros.md 
theme:
  name: 'material'
  logo: 'images/logolight.png'
  favicon: 'images/logodark.png'
  palette:
    primary: purple
    accent: purple




markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: FrizzyElectronics
repo_url: https://github.com/FrizzyElectronics/ElementalKitDocs